package:
  name: grpc-cpp
  version: 1.7.1

source:
  git_url: https://github.com/grpc/grpc.git
  git_rev: v1.7.1

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.

requirements:
  build:
    - toolchain
    - autoconf
    - libtool
    - protobuf >=3.4.1,<3.5.0a0
    - gflags
    - gtest
  run:
    - protobuf >=3.4.1,<3.5.0a0
