package:
  name: grpc-cpp
  version: {{ environ['VERSION'] }}

source:
  git_url: https://github.com/grpc/grpc.git
  git_rev: v{{ environ['VERSION'] }}

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.

requirements:
  build:
    - {{ compiler('cxx') }}
    - autoconf
    - libtool
  host:
    - c-ares >=1.14.0
    - protobuf >=3.6.0
    - gflags
    - gtest
    - zlib >=1.2.11
  run:
    - c-ares >=1.14.0
    - protobuf >=3.6.0
    - zlib >=1.2.11
