language: generic

os:
  - linux

install:
  # Install Anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - conda activate base
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge

build:
  script_env:
   - VERSION
   - CONDA_BLD_PATH

after_success:
  - test $TRAVIS_BRANCH = "master" && conda install conda-build anaconda-client && bash recipe/conda_upload.sh
